AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Dairy Farm Shift Management System'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref ShiftManagementTable
        ENVIRONMENT: !Ref Environment

Resources:
  # DynamoDB Table
  ShiftManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'dairy-shifts-${Environment}'
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2

  # API Gateway
  ShiftManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      BinaryMediaTypes:
        - image/x-icon
        - image/*
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions
  WebAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-web-app-${Environment}'
      CodeUri: src/
      Handler: web_app.lambda_handler
      Events:
        WebApp:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /
            Method: GET
        WebAppHtml:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /{filename}
            Method: GET
        Favicon:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /favicon.ico
            Method: GET

  ShiftCrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-shift-crud-${Environment}'
      CodeUri: src/
      Handler: shift_crud.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        GetShiftsByDate:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/by-date/{date}
            Method: GET
        CreateShift:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts
            Method: POST
        UpdateShift:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/by-id/{id}
            Method: PUT
        DeleteShift:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/by-id/{id}
            Method: DELETE

  EmployeeManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-employee-management-${Environment}'
      CodeUri: src/
      Handler: employee_management.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        GetEmployees:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees
            Method: GET
        CreateEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees
            Method: POST
        GetEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees/{id}
            Method: GET
        UpdateEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees/{id}
            Method: PUT
        DeleteEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees/{id}
            Method: DELETE
        GetEmployeeVacationUsed:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees/{id}/vacation-used
            Method: GET

  EmployeeShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-employee-shifts-${Environment}'
      CodeUri: src/
      Handler: employee_shifts.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        GetEmployeeShifts:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /employees/{id}/shifts
            Method: GET

  TaskManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-task-management-${Environment}'
      CodeUri: src/
      Handler: task_management_crud.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        GetTasks:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /tasks
            Method: GET
        CreateTask:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /tasks
            Method: POST
        GetTask:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /tasks/{id}
            Method: GET
        UpdateTask:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /tasks/{id}
            Method: PUT
        DeleteTask:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /tasks/{id}
            Method: DELETE

  ShiftAssignmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-shift-assignment-${Environment}'
      CodeUri: src/
      Handler: shift_assignment.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        AutoAssign:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/assign
            Method: POST
        GenerateMonthly:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/generate-monthly
            Method: POST
        GetShiftsByMonth:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /shifts/by-month/{month}
            Method: GET

  SettingsManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'dairy-settings-management-${Environment}'
      CodeUri: src/
      Handler: settings_management.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShiftManagementTable
      Events:
        RequirementsGlobalDefault:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /requirements/global-default
            Method: ANY
        RequirementsMonthly:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /requirements/default/{month}
            Method: ANY
        RequirementsDaily:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /requirements/daily/{date}
            Method: ANY
        SettingsConfirmation:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /settings/confirmation
            Method: ANY
        SettingsVacationDefault:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftManagementApi
            Path: /settings/vacation-default
            Method: ANY

Outputs:
  WebAppUrl:
    Description: 'Web Application URL'
    Value: !Sub 'https://${ShiftManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'
  
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ShiftManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  
  TableName:
    Description: 'DynamoDB table name'
    Value: !Ref ShiftManagementTable